version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    env_file:
      - .env
  sio:
    build:
      context: .
      dockerfile: docker/sio/Dockerfile
    network_mode: "host"
    environment:
      - PORT=8000
    env_file:
      - .env
    
  