mod core;
mod factory;
mod game;
mod geometry;
mod map;
mod player;
mod probe;
mod random;

pub use self::core::*;
use self::factory::*;
pub use self::geometry::*;
use self::map::*;
use self::player::*;
use self::probe::*;

pub struct GameConfig {
    /// dimension of the map (unit: coord),
    dim: Coord,

    /// number of players in the game
    n_player: u32,

    /// money players start with
    initial_money: f64,

    /// initial number of probes to start with (must be smaller
    /// than `factory_max_probe`)
    initial_n_probes: u32,

    /// base income that each player receive unconditionally
    base_income: f64,

    /// minimal occupation value on tile required to build a building (factory/turret)
    building_occupation_min: u32,

    /// amount to pay to build a new factory
    factory_price: f64,

    /// maximal number of probe generated by a factory
    factory_max_probe: u32,

    /// delay to wait to build a probe from the factory (sec)
    factory_build_probe_delay: f64,

    /// maximal occupation value that can be reached
    max_occupation: u32,

    /// speed of the probe in coordinate/sec
    probe_speed: f64,

    /// amount to pay to produce one probe
    probe_price: f64,

    /// delay to wait claim a tile, the probe can be manually moved but not claim
    /// another tile during the delay (see Probe `is_claiming` flag for details)
    probe_claim_delay: f64,

    /// Costs of possessing one probe (computed in the player's income)
    probe_maintenance_costs: f64,

    /// amount to pay to build a new turret
    turret_price: f64,

    /// delay to wait for the turret between two fires (sec)
    turret_fire_delay: u32,

    /// scope of the turret (unit| coord)
    turret_scope: f64,

    /// Costs of possessing one turret (computed in the player's income)
    turret_maintenance_costs: f64,

    /// factor of how the occupation level of a tile reflects on its income,
    /// as `income = occupation * rate`
    income_rate: f64,

    /// probability that a tile with maximum occupation lose 1 occupation
    deprecate_rate: f64,
}
